#include "../includes/menu.h"
#include "../includes/performance.h"
#include "../third_party/microui.h"
#include <GL/gl.h>
#include <GL/glut.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdarg.h>

extern Pontos g_clicks;
extern int precisa_refazer_curva;
extern void onMouse(int button,int state,int x,int y);
extern void onMouseMove(int x,int y);
extern void onMotion(int x,int y);

EstadoAplicacao estado_atual={MODO_CRIAR_PONTO,MODO_POLIGONO_ABERTO,MODO_CURVA_HERMITE,NENHUMA,"0","0",0};
int menu_largura=200;
Botoes botoes;
BotoesOperacoes botoes_operacoes[4];
static mu_Context ui; static int ui_initialized=0; static int janela_largura=800,janela_altura=800; static int mouse_x=0,mouse_y=0,mostrar_metricas=0;
static void mu_labelf(mu_Context*c,const char*f,...){char b[512];va_list a;va_start(a,f);vsnprintf(b,sizeof(b),f,a);va_end(a);mu_label(c,b);}
static int text_width(mu_Font f,const char*t,int n){(void)f;int w=0;for(int i=0;i<n;i++)w+=((unsigned char)t[i]<128)?glutStrokeWidth(GLUT_STROKE_ROMAN,t[i])/8:8;return w;}
static int text_height(mu_Font f){(void)f;return 16;}
static void draw_rect(mu_Rect r,mu_Color c,int filled){glColor4ub(c.r,c.g,c.b,c.a);glBegin(filled?GL_QUADS:GL_LINE_LOOP);glVertex2i(r.x,r.y);glVertex2i(r.x+r.w,r.y);glVertex2i(r.x+r.w,r.y+r.h);glVertex2i(r.x,r.y+r.h);glEnd();}
static void draw_text(const mu_TextCommand*c){glColor4ub(c->color.r,c->color.g,c->color.b,c->color.a);glPushMatrix();glTranslatef(c->pos.x,c->pos.y+12,0);glScalef(.125f,.125f,1);int n=(int)strlen(c->str);for(int i=0;i<n;i++)if((unsigned char)c->str[i]<128)glutStrokeCharacter(GLUT_STROKE_ROMAN,c->str[i]);glPopMatrix();}
static void render_commands(void){mu_Command*c=NULL;while(mu_next_command(&ui,&c)){switch(c->type){case MU_COMMAND_CLIP:glEnable(GL_SCISSOR_TEST);glScissor(c->clip.rect.x,janela_altura-c->clip.rect.y-c->clip.rect.h,c->clip.rect.w,c->clip.rect.h);break;case MU_COMMAND_RECT:draw_rect(c->rect.rect,c->rect.color,1);break;case MU_COMMAND_TEXT:draw_text(&c->text);break;default:break;}}glDisable(GL_SCISSOR_TEST);}
static int lx(void){return mouse_x-(janela_largura-menu_largura);} static void begin_frame(void){mu_begin(&ui);mu_input_mousemove(&ui,lx(),mouse_y);} static void changed(void){precisa_refazer_curva=1;glutPostRedisplay();}
static void sidebar(void){if(!mu_begin_window_ex(&ui,"menu",mu_rect(0,0,menu_largura,janela_altura),MU_OPT_NOCLOSE|MU_OPT_NORESIZE|MU_OPT_NOTITLE))return;mu_layout_row(&ui,1,(int[]){-1},26);mu_label(&ui,"Curvas Parametricas");mu_layout_row(&ui,1,(int[]){-1},30);if(mu_button(&ui,"Criar Ponto")){estado_atual.criacao_ou_selecao=MODO_CRIAR_PONTO;estado_atual.operacao=NENHUMA;changed();}if(mu_button(&ui,"Apagar Ponto")){estado_atual.criacao_ou_selecao=MODO_APAGAR_PONTO;changed();}if(mu_button(&ui,"Selecionar Ponto")){estado_atual.criacao_ou_selecao=MODO_SELECIONAR_PONTO;changed();}if(mu_button(&ui,"Operar Poligono")){estado_atual.criacao_ou_selecao=MODO_SELECIONAR_POLIGONO;changed();}if(mu_button(&ui,"Selecionar Curva")){estado_atual.criacao_ou_selecao=MODO_SELEICIONAR_CURVA;changed();}mu_layout_row(&ui,1,(int[]){-1},22);mu_label(&ui,"Poligono");mu_layout_row(&ui,2,(int[]){-1,-1},28);if(mu_button(&ui,estado_atual.poligono==MODO_POLIGONO_ABERTO?"[x] Aberto":"Aberto")){estado_atual.poligono=MODO_POLIGONO_ABERTO;changed();}if(mu_button(&ui,estado_atual.poligono==MODO_POLIGONO_FECHADO?"[x] Fechado":"Fechado")){estado_atual.poligono=MODO_POLIGONO_FECHADO;changed();}mu_layout_row(&ui,1,(int[]){-1},22);mu_label(&ui,"Tipo de curva");mu_layout_row(&ui,2,(int[]){-1,-1},28);if(mu_button(&ui,estado_atual.curva==MODO_CURVA_HERMITE?"[x] Hermite":"Hermite")){estado_atual.curva=MODO_CURVA_HERMITE;changed();}if(mu_button(&ui,estado_atual.curva==MODO_CURVA_BEZIER?"[x] Bezier":"Bezier")){estado_atual.curva=MODO_CURVA_BEZIER;changed();}if(mu_button(&ui,estado_atual.curva==MODO_CURVA_BSPLINE?"[x] B-Spline":"B-Spline")){estado_atual.curva=MODO_CURVA_BSPLINE;changed();}if(mu_button(&ui,estado_atual.curva==MODO_CURVA_CATMULLROM?"[x] Catmull-Rom":"Catmull-Rom")){estado_atual.curva=MODO_CURVA_CATMULLROM;changed();}if(estado_atual.criacao_ou_selecao==MODO_SELECIONAR_POLIGONO){mu_layout_row(&ui,1,(int[]){-1},22);mu_label(&ui,"Operacoes");mu_layout_row(&ui,2,(int[]){-1,-1},28);if(mu_button(&ui,"Translacao")){estado_atual.operacao=TRANSLACAO;changed();}if(mu_button(&ui,"Rotacao")){estado_atual.operacao=ROTACAO;changed();}if(mu_button(&ui,"Escala")){estado_atual.operacao=ESCALA;changed();}if(mu_button(&ui,"Shear")){estado_atual.operacao=SHEAR;changed();}}mu_layout_row(&ui,1,(int[]){-1},34);if(mu_button(&ui,"Metricas de desempenho"))mostrar_metricas=1;mu_end_window(&ui);}
static void status(void){char a[64],b[64];snprintf(a,sizeof(a),"Pontos de controle: %d",g_clicks.quantidade_atual);snprintf(b,sizeof(b),"Nuvem de pontos: %d",estado_atual.qtd_nuvem_pontos_number);if(!mu_begin_window_ex(&ui,"status",mu_rect(5,janela_altura-86,menu_largura-10,80),MU_OPT_NOCLOSE|MU_OPT_NORESIZE|MU_OPT_NOTITLE))return;mu_layout_row(&ui,1,(int[]){-1},22);mu_Rect ra=mu_layout_next(&ui);mu_draw_control_text(&ui,a,ra,MU_COLOR_TEXT,0);mu_layout_row(&ui,1,(int[]){-1},22);mu_Rect rb=mu_layout_next(&ui);mu_draw_control_text(&ui,b,rb,MU_COLOR_TEXT,0);if(mu_mouse_over(&ui,ra)){mu_Rect t=mu_rect(ra.x,ra.y-30,ra.w,26);mu_draw_rect(&ui,t,mu_color(30,35,42,245));mu_draw_text(&ui,ui.style->font,"Quantidade de pontos usados para definir a forma da curva.",55,mu_vec2(t.x+4,t.y+5),mu_color(240,240,240,255));}else if(mu_mouse_over(&ui,rb)){mu_Rect t=mu_rect(rb.x,rb.y-30,rb.w,26);mu_draw_rect(&ui,t,mu_color(30,35,42,245));mu_draw_text(&ui,ui.style->font,"Quantidade de pontos amostrados como referencia geometrica.",60,mu_vec2(t.x+4,t.y+5),mu_color(240,240,240,255));}mu_end_window(&ui);}
static void metrics(void){if(!mostrar_metricas)return;if(!mu_begin_window_ex(&ui,"metricas",mu_rect(5,5,menu_largura-10,janela_altura-10),MU_OPT_HOLDFOCUS|MU_OPT_NOCLOSE))return;const PerformanceMetric*m=performance_current();mu_label(&ui,"METRICAS DE DESEMPENHO");if(mu_button(&ui,"Fechar metricas")){mostrar_metricas=0;mu_end_window(&ui);return;}mu_labelf(&ui,"Maquina: %s",m->machine_id);mu_labelf(&ui,"CPU: %s",m->processor);mu_labelf(&ui,"RAM: %s",m->memory);mu_labelf(&ui,"GPU: %s",m->gpu);mu_labelf(&ui,"Arq: %s",m->architecture);mu_labelf(&ui,"OS: %s",m->os);mu_labelf(&ui,"Curva: %s",m->curve[0]?m->curve:"-");mu_labelf(&ui,"Geracao: %.6f ms",m->generation_ms);mu_labelf(&ui,"Desenho: %.6f ms",m->drawing_ms);mu_labelf(&ui,"Pontos: %zu",m->points_generated);mu_labelf(&ui,"Buffer curva: %zu / %zu",m->buffer_used,m->buffer_capacity);mu_labelf(&ui,"Buffer controle: %zu / %zu",m->control_buffer_used,m->control_buffer_capacity);mu_label(&ui,"Historico por curva");PerformanceMetric v[64];int n=performance_history(v,64);for(int i=0;i<n;i++)mu_labelf(&ui,"%s | %s | gen %.4f | draw %.4f | pts %zu",v[i].timestamp,v[i].curve,v[i].generation_ms,v[i].drawing_ms,v[i].points_generated);mu_label(&ui,"Dados salvos em data/performance.csv");mu_end_window(&ui);}
void atualizar_dimensoes_menu(void){janela_largura=glutGet(GLUT_WINDOW_WIDTH);janela_altura=glutGet(GLUT_WINDOW_HEIGHT);menu_largura=(int)(janela_largura*.15f);if(menu_largura<150)menu_largura=150;if(menu_largura>janela_largura-100)menu_largura=janela_largura-100;}
void inicializar_menu(void){atualizar_dimensoes_menu();mu_init(&ui);ui.style->font=(mu_Font)GLUT_STROKE_ROMAN;ui.text_width=text_width;ui.text_height=text_height;ui.style->size=mu_vec2(80,16);ui.style->padding=5;ui.style->spacing=4;ui.style->title_height=24;ui.style->scrollbar_size=12;ui_initialized=1;}
void menu_mouse_move(int x,int y){mouse_x=x;mouse_y=y;if(ui_initialized)mu_input_mousemove(&ui,x-(janela_largura-menu_largura),y);}
void menu_mouse_button(int button,int state,int x,int y){mouse_x=x;mouse_y=y;if(!ui_initialized)return;int b=button==GLUT_LEFT_BUTTON?MU_MOUSE_LEFT:button==GLUT_RIGHT_BUTTON?MU_MOUSE_RIGHT:0;if(!b)return;int xlocal=x-(janela_largura-menu_largura);if(state==GLUT_DOWN)mu_input_mousedown(&ui,xlocal,y,b);else mu_input_mouseup(&ui,xlocal,y,b);}
void menu_mouse_scroll(int direction,int x,int y){mouse_x=x;mouse_y=y;if(ui_initialized)mu_input_scroll(&ui,0,direction);}
void menu_render(void){if(!ui_initialized)return;atualizar_dimensoes_menu();glMatrixMode(GL_PROJECTION);glLoadIdentity();glOrtho(0,menu_largura,janela_altura,0,-1,1);glMatrixMode(GL_MODELVIEW);glLoadIdentity();begin_frame();sidebar();status();metrics();mu_end(&ui);render_commands();}
int menu_bloqueia_desenho(void){return mostrar_metricas;}
void menu_shutdown(void){ui_initialized=0;}
void menu_mouse_dispatch(int button,int state,int x,int y){int w=glutGet(GLUT_WINDOW_WIDTH);if(x>=w-menu_largura){menu_mouse_button(button,state,x,y);return;}onMouse(button,state,x,y);}
void menu_passive_motion_dispatch(int x,int y){int w=glutGet(GLUT_WINDOW_WIDTH);if(x>=w-menu_largura){menu_mouse_move(x,y);return;}onMouseMove(x,y);}
void menu_motion_dispatch(int x,int y){int w=glutGet(GLUT_WINDOW_WIDTH);if(x>=w-menu_largura){menu_mouse_move(x,y);return;}onMotion(x,y);}
void desenhar_botoes_menu(void){menu_render();}
void desenhar_info(void){}
